#FROM nvidia/cuda:11.2.2-base-ubuntu20.04
# use slim python 3.9
FROM python:3.9-slim-buster

WORKDIR /app

# Install dependencies
# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
#     python3.9 \
#     python3-pip \
#     ffmpeg

# Create a symbolic link for Python
# RUN ln -s /usr/bin/python3.9 /usr/bin/python

# # Install poetry and dependencies
# RUN pip install poetry
# RUN poetry config virtualenvs.create false
# RUN poetry install --no-dev
# RUN poetry shell
RUN pip install fastapi
RUN pip install uvicorn
RUN pip install python-multipart
RUN pip install openai
RUN pip install python-dotenv
# RUN pip install openai-whisper

ENV PYTHONUNBUFFERED=

COPY ./src /app
COPY .env /app

# start an interactive bash session
# ENTRYPOINT ["/bin/bash"]
# CMD ["uvicorn", "blank-to-bard.stt_api:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uvicorn", "blank_to_bard.stt_openai_api:app", "--host", "0.0.0.0", "--port", "8000"]
