FROM python:3.9-slim-buster

RUN pip install fastapi uvicorn python-multipart google-auth google-auth-httplib2 google-auth-oauthlib google-api-python-client

WORKDIR /app

COPY ./src/blank_to_bard/middleman_auth.py /app
COPY .env /app
EXPOSE 8000

CMD ["uvicorn", "middleman_auth:app", "--host", "0.0.0.0", "--port", "8000"]
